### ISSUE TITLE
Exception when calling ReportsV20210630Api->getReport: gzdecode(): data error

### ISSUE THREAD

**Issue by DomuITteam** [jlevers/selling-partner-api#559] opened 2023-06-21 07:07 UTC
## Problem description:

A new error appeared around 3:45 AM BST when trying to retrieve GET_MERCHANT_LISTINGS_ALL_DATA report using **getReport** function from **ReportsV20210630Api** class. The last successful attempt logged was at 3:32 AM BST.

No changes to the code were made during that time. [Amazon SP-API health dashboard](https://sellercentral.amazon.com/sp-api-status) doesn't indicate any issues for EU endpoint.
## Error:

```
Exception when calling ReportsV20210630Api->getReport: gzdecode(): data error
```

EDIT: We're investigating if [tonight's update](https://developer-docs.amazon.com/sp-api/changelog/changes-to-the-acceptable-use-policy) has got anything to do with it.

**Comment by widdydev** [comment] 2023-06-21 07:19
We're getting the same error for the following report types:

- GET_MERCHANT_LISTINGS_ALL_DATA
- GET_SALES_AND_TRAFFIC_REPORT
- GET_COUPON_PERFORMANCE_REPORT
- GET_LEDGER_SUMMARY_VIEW_DATA

**Comment by DomuITteam** [comment] 2023-06-21 07:39
So it fails in [ReportsV20210630Api.php](https://github.com/jlevers/selling-partner-api/blob/a7f90fcfc2f7f8b09ac96bdfc92ce411b3d54524/lib/Api/ReportsV20210630Api.php#L1477-L1486), lines 1477 to 1486:

```
$responseBody = $response->getBody();
switch($statusCode) {
    case 200:
        if ('\SellingPartnerApi\Model\ReportsV20210630\Report' === '\SplFileObject') {
            $content = $responseBody; //stream goes to serializer
        } else {
            $content = (string) $responseBody;
        }


        return ObjectSerializer::deserialize($content, '\SellingPartnerApi\Model\ReportsV20210630\Report', $response->getHeaders());
```

The code comes back successfully with code 200, but it seems like it fails on the IF statement.

**Comment by widdydev** [comment] 2023-06-21 09:56
Ok now we can definitely say what the problem here is.:
First of all the library uses the GuzzleHttp client as you can see [here](https://github.com/jlevers/selling-partner-api/blob/a7f90fcfc2f7f8b09ac96bdfc92ce411b3d54524/lib/Document.php#L98).
According to the GuzzleHttp [docs](https://docs.guzzlephp.org/en/5.3/clients.html?highlight=gzip#decode-content) the client will try to automatically decode the response per default.
Sometimes the response from amazon does include the header that signals the client to decode the response, meaning that we're going to pass already decoded data to the `gzdecode`method.
In my opinion we should opt out by passing ` 'decode_content' => false` to the request like so:
```
 $response = $this->client->request('GET', $this->url, [
    'stream' => true,
    'decode_content' => false,
]);
```

With that it is deterministic that we'll always receive an undecoded response, that we can then feed into the `gzdecode`method.

**Comment by HeBuguM** [comment] 2023-06-21 14:43
Same problem here, Amazon is saying it's GZIP but the content is already decoded.
I can confirm @widdydev suggestion, passing `'decode_content' => false` to the request solves the issue.

**Comment by jlevers** [comment] 2023-06-24 19:30
Based on https://github.com/amzn/selling-partner-api-docs/issues/3200, I think this issue is probably resolved, so I'm going to close this issue. @widdydev, if you still want to follow up on your PR, I'll still merge it since it will prevent this issue in the future if Amazon messes up again

**Closed by jlevers** 2023-06-24 19:30 UTC
