### ISSUE TITLE
Getorders not getting buyer information and address

### ISSUE THREAD

**Issue by sunil11475-dev** [jlevers/selling-partner-api#238] opened 2022-04-01 16:09 UTC
Hi,

I am trying to call getOrders to get all order information but its getting empty array. I have PII approved app and Yes "Direct-to-Consumer Delivery" and The Restricted Data Token (RDT) enabled on my app.

With `$data_elements = array("buyerInfo", "shippingAddress");` I am getting response `array()` no array

```php
$data_elements = array("buyerInfo", "shippingAddress");
do {
    try {
        $response = $apiInstance->getOrders($marketplace_ids, $created_after, $created_before, $last_updated_after, $last_updated_before, $order_statuses, $fulfillment_channels, $payment_methods, $buyer_email, $seller_order_id, $max_results_per_page, $easy_ship_shipment_statuses, $next_token, $amazon_order_ids, $data_elements);
        $result = $response['payload'][orders];
    } catch (Exception $e) {
        echo 'Exception when calling OrdersV0Api->getOrders: ', $e->getMessage(), PHP_EOL;
    }
}
```

If i call with empty `$data_elements = array();`, its getting array but no buyer information and address.

```
[shipping_address] => SellingPartnerApi\Model\Orders\Address Object
(
[container:protected] => Array
(
[name] =>
[address_line1] =>
[address_line2] =>
[address_line3] =>
[city] => LUTON
[county] =>
[district] =>
[state_or_region] =>
[municipality] =>
[postal_code] => LU2 0BJ
[country_code] => GB
[phone] =>
[address_type] =>
)

)

[buyer_info] => SellingPartnerApi\Model\Orders\BuyerInfo Object
(
[container:protected] => Array
(
[buyer_email] => t10trasdfx0cq2@marketplace.amazon.co.uk
[buyer_name] =>
[buyer_county] =>
[buyer_tax_info] =>
[purchase_order_number] =>
)
)
```

**Comment by jlevers** [comment] 2022-04-02 18:52
For any `getOrders` parameters that you're not actually using, pass `null`. So it should look something like this:

```php
$data_elements = ["buyerInfo", "shippingAddress"];
try {
    $response = $apiInstance->getOrders($marketplace_ids, $created_after, null, null, null, null, null, null, null, null, null, null, null, null, $data_elements);
    $result = $response['payload']['orders'];
} catch (Exception $e) {
    echo 'Exception when calling OrdersV0Api->getOrders: ', $e->getMessage(), PHP_EOL;
}
```

Also, if you didn't generate a new refresh token for your application after you were granted PII access, you'll need to do that.

**Comment by sunil11475-dev** [comment] 2022-04-03 12:42
Hi,

Thanks, I tried with `null` and got below array - no data /orders

```
SellingPartnerApi\Model\Orders\GetOrdersResponse Object
(
    [container:protected] => Array
        (
            [payload] => SellingPartnerApi\Model\Orders\OrdersList Object
                (
                    [container:protected] => Array
                        (
                            [orders] => Array
                                (
                                )

                            [next_token] => 
                            [last_updated_before] => 
                            [created_before] => 2022-04-03T12:38:48Z
                        )

                )

            [errors] => 
```

**Comment by balicekt** [comment] 2022-04-05 07:38
Hello, I have the same problem now. Any solution of this?

**Comment by sunil11475-dev** [comment] 2022-04-05 18:07
@balicekt No, I have opened case 4 weeks ago on Amazon developer and it just going round and round. they come back every time ask for -

```
> I would like to inform you that I reached out to the concerned team, and they have requested for the request and response, untruncated, including headers and as a .txt format file attachment.
> This request and response is required for the operation creating the RDT operation from Tokens API.
```
Once I provide that they go quite for week and ask again for same details. 

One more thing if i make call for `getOrderAddress() ` and `getOrderBuyerInfo()` separately its bring the data.

But then i have to make 4 calls - one for `getOrders() ` ( for orders list)
for each order :-
one for `getOrderAddress` and one for `getOrderBuyerInfo` and last one for `getOrderItems()` to complete the order data.

If Any body have any idea, please share.

**Comment by balicekt** [comment] 2022-04-05 21:00
Yes same here and exactly same with the Amazon support. So I put this line and for now is working: 

$order->setShippingAddress($apiInstance->getOrderAddress($order->getAmazonOrderId())->getPayload()->getShippingAddress());

**Comment by jlevers** [comment] 2022-04-06 03:34
Weird, I'm just not able to reproduce this -- when I make the `getOrders` call with `$data_elements` set to `['shippingAddress', 'buyerInfo']`, I get all the expected data. This seems like it's probably an issue with Amazon, not with my library, so I recommend opening a support case (which it sounds like both of you have) and creating an issue in the [main docs repository](https://github.com/amzn/selling-partner-api-docs/issues).

I'm going to close this issue since I'm 99% sure it's not caused by my library, but feel free to keep discussing here, and please re-open the issue if you think it actually is a problem with the library.

**Closed by jlevers** 2022-04-06 03:34 UTC

**Comment by sunil11475-dev** [comment] 2022-04-13 12:53
> Yes same here and exactly same with the Amazon support. So I put this line and for now is working:
> 
> $order->setShippingAddress($apiInstance->getOrderAddress($order->getAmazonOrderId())->getPayload()->getShippingAddress());

@balicekt Can you please tell me where you put this line in code - 

$order->setShippingAddress($apiInstance->getOrderAddress($order->getAmazonOrderId())->getPayload()->getShippingAddress());

**Comment by sunil11475-dev** [comment] 2022-04-13 14:45
@balicekt Thanks for your response - How many orders you fetching from this code?

**Comment by balicekt** [comment] 2022-04-13 14:47
we are now still in developing mode so we don't know yet.

**Comment by sunil11475-dev** [comment] 2022-04-13 15:03
> `getOrders`

I have question. When we call to `getOrders `operation, its calls to `RestrictedDataToken` then get data from amazon? 

When we are using below elements -
`$data_elements = ["buyerInfo", "shippingAddress"];`

Amazon asking - "I would like to request you to please confirm using the RDT for calling the getOrders operation"

Can you please help.

**Comment by sunil11475-dev** [comment] 2022-04-13 15:03
> Weird, I'm just not able to reproduce this -- when I make the `getOrders` call with `$data_elements` set to `['shippingAddress', 'buyerInfo']`, I get all the expected data. This seems like it's probably an issue with Amazon, not with my library, so I recommend opening a support case (which it sounds like both of you have) and creating an issue in the [main docs repository](https://github.com/amzn/selling-partner-api-docs/issues).
> 
> I'm going to close this issue since I'm 99% sure it's not caused by my library, but feel free to keep discussing here, and please re-open the issue if you think it actually is a problem with the library.

I have question. When we call to `getOrders `operation, its calls to `RestrictedDataToken` then get data from amazon?

When we are using below elements -
`$data_elements = ["buyerInfo", "shippingAddress"];`

Amazon asking - "I would like to request you to please confirm using the RDT for calling the getOrders operation"

Can you please help.

**Comment by sunil11475-dev** [comment] 2022-04-13 15:09
> we are now still in developing mode so we don't know yet.

That the issue, 2 week ago I put my code live mode, thought everything is fine but start getting below issue "buyerInfo", "shippingAddress"

`"TooManyRequestsException" error.`
sometime the order address call brings empty array.

Only 20 - 50 orders.

**Comment by balicekt** [comment] 2022-04-13 15:14
To be honest => now I tried to add $data_elements = ["buyerInfo", "shippingAddress"]; and don't need the line above. Everything working fine Im getting full address.

I think the library should make RDT automatically.

**Comment by sunil11475-dev** [comment] 2022-04-13 15:35
@balicekt 
I have updated the library folder and still with `$data_elements = ["buyerInfo", "shippingAddress"];` I am getting empty array

```
SellingPartnerApi\Model\Orders\GetOrdersResponse Object
(
    [container:protected] => Array
        (
            [payload] => SellingPartnerApi\Model\Orders\OrdersList Object
                (
                    [container:protected] => Array
                        (
                            [orders] => Array
                                (
                                )

                            [next_token] => 
                            [last_updated_before] => 
                            [created_before] => 2022-04-13T14:45:42Z
                        )

                )

```

**Comment by sunil11475-dev** [comment] 2022-04-14 05:32
@jlevers @balicekt 
Can you please check my app registration; is it correct -

![Ama-App-reg](https://user-images.githubusercontent.com/82319811/163319999-dc536f0a-c1b9-4407-b7dd-ebe2841950ab.jpg)

**Comment by seannycrow** [comment] 2022-04-14 14:45
Hi,

First the OP doesn't seem to have the right number of parameters in his GetOrders call, if you look at the doc it's:

$result = $apiInstance->getOrders($marketplace_ids, $created_after, $created_before, $last_updated_after, $last_updated_before, $order_statuses, $fulfillment_channels, $payment_methods, $buyer_email, $seller_order_id, $max_results_per_page, $easy_ship_shipment_statuses, $next_token, $amazon_order_ids, $actual_fulfillment_supply_source_id, $is_ispu, $store_chain_store_id, $data_elements);

so if you put "null" in those not used it gives us:
$result= $apiInstance->getOrders($marketplace_ids,$created_after,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,$data_elements);
And NOT:
$response = $apiInstance->getOrders($marketplace_ids,$created_after,null,null,null,null,null,null,null,null,null,null,null,null,$data_elements);

So I'll guess that's why he is getting an empty array (I get the same thing if I use his code instead of mine).

THE PROBLEM is that even if I pass the right number of parameters I get an error 400 :

`$marketplace_ids=array('A13V1IB3VIYZZH'); // string[] | A comma-delimited list of Amazon marketplace identifiers for the request.								

$dateRecupCommandeAfter=preg_replace("/\+.*/",'',date("c", strtotime(date("Y-m-d H:i:s")." -1 day")));
$created_after = $dateRecupCommandeAfter; // string | A date used for selecting orders created after (or at) a specified time. Only orders placed after the specified time are returned. Either the CreatedAfter parameter or the LastUpdatedAfter parameter is required. Both cannot be empty. The date must be in ISO 8601 format.
$created_before = null; // string | A date used for selecting orders created before (or at) a specified time. Only orders placed before the specified time are returned. The date must be in ISO 8601 format.
$last_updated_after = null; // string | A date used for selecting orders that were last updated after (or at) a specified time. An update is defined as any change in order status, including the creation of a new order. Includes updates made by Amazon and by the seller. The date must be in ISO 8601 format.
$last_updated_before = null; // string | A date used for selecting orders that were last updated before (or at) a specified time. An update is defined as any change in order status, including the creation of a new order. Includes updates made by Amazon and by the seller. The date must be in ISO 8601 format.
$order_statuses = null; // string[] | A list of OrderStatus values used to filter the results. Possible values: PendingAvailability (This status is available for pre-orders only. The order has been placed, payment has not been authorized, and the release date of the item is in the future.); Pending (The order has been placed but payment has not been authorized); Unshipped (Payment has been authorized and the order is ready for shipment, but no items in the order have been shipped); PartiallyShipped (One or more, but not all, items in the order have been shipped); Shipped (All items in the order have been shipped); InvoiceUnconfirmed (All items in the order have been shipped. The seller has not yet given confirmation to Amazon that the invoice has been shipped to the buyer.); Canceled (The order has been canceled); and Unfulfillable (The order cannot be fulfilled. This state applies only to Multi-Channel Fulfillment orders.).
$fulfillment_channels = array('MFN'); // string[] | A list that indicates how an order was fulfilled. Filters the results by fulfillment channel. Possible values: AFN (Fulfillment by Amazon); MFN (Fulfilled by the seller).
$payment_methods = null; // string[] | A list of payment method values. Used to select orders paid using the specified payment methods. Possible values: COD (Cash on delivery); CVS (Convenience store payment); Other (Any payment method other than COD or CVS).
$buyer_email = null; // string | The email address of a buyer. Used to select orders that contain the specified email address.
$seller_order_id = null; // string | An order identifier that is specified by the seller. Used to select only the orders that match the order identifier. If SellerOrderId is specified, then FulfillmentChannels, OrderStatuses, PaymentMethod, LastUpdatedAfter, LastUpdatedBefore, and BuyerEmail cannot be specified.
$max_results_per_page = null; // int | A number that indicates the maximum number of orders that can be returned per page. Value must be 1 - 100. Default 100.
$easy_ship_shipment_statuses =null;; // string[] | A list of EasyShipShipmentStatus values. Used to select Easy Ship orders with statuses that match the specified  values. If EasyShipShipmentStatus is specified, only Amazon Easy Ship orders are returned.Possible values: PendingPickUp (Amazon has not yet picked up the package from the seller). LabelCanceled (The seller canceled the pickup). PickedUp (Amazon has picked up the package from the seller). AtOriginFC (The packaged is at the origin fulfillment center). AtDestinationFC (The package is at the destination fulfillment center). OutForDelivery (The package is out for delivery). Damaged (The package was damaged by the carrier). Delivered (The package has been delivered to the buyer). RejectedByBuyer (The package has been rejected by the buyer). Undeliverable (The package cannot be delivered). ReturnedToSeller (The package was not delivered to the buyer and was returned to the seller). ReturningToSeller (The package was not delivered to the buyer and is being returned to the seller).
$next_token = null; // string | A string token returned in the response of your previous request.
$amazon_order_ids = null; // string[] | A list of AmazonOrderId values. An AmazonOrderId is an Amazon-defined order identifier, in 3-7-7 format.
$actual_fulfillment_supply_source_id = null; // string | Denotes the recommended sourceId where the order should be fulfilled from.
$is_ispu = null; // bool | When true, this order is marked to be picked up from a store rather than delivered.
$store_chain_store_id = null; // string | The store chain store identifier. Linked to a specific store in a store chain.
// $data_elements = array('buyerInfo','shippingAddress'); // string[] | An array of restricted order data elements to retrieve (valid array elements are \"buyerInfo\" and \"shippingAddress\")
$data_elements = ["buyerInfo", "shippingAddress"]; // string[] | An array of restricted order data elements to retrieve (valid array elements are \"buyerInfo\" and \"shippingAddress\")


try {	
    // $response = $apiInstance2->getOrders($marketplace_ids,$created_after,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,$data_elements);
	$response = $apiInstance2->getOrders($marketplace_ids, $created_after, $created_before, $last_updated_after, $last_updated_before, $order_statuses, $fulfillment_channels, $payment_methods, $buyer_email, $seller_order_id, $max_results_per_page, $easy_ship_shipment_statuses, $next_token, $amazon_order_ids, $actual_fulfillment_supply_source_id, $is_ispu, $store_chain_store_id, $data_elements);
	$result = $response['payload']['orders'];

	print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling OrdersApi->getOrders: ', $e->getMessage(), PHP_EOL;
}`

But if I juste remove $data_elements as last parameter then the call passes no problems (just without the adress, etc.).

**Comment by jlevers** [comment] 2022-04-14 16:01
@sunil11475-dev delegating PII access does *not* mean that you can retrieve PII, so between that and what @seannycrow pointed out, that's why you're not getting any of the restricted data.

@seannycrow, do you have PII access, or are you just delegating it? Again, delegation doesn't give you access to PII, it just allows someone else to retrieve PII on the behalf of your application.

**Comment by sunil11475-dev** [comment] 2022-04-14 17:34
@jlevers  I was try using your provided example code (which is my mistake didn't checked)
   ` $response = $apiInstance->getOrders($marketplace_ids, $created_after, null, null, null, null, null, null, null, null, null, null, null, null, $data_elements);`

and then i thought i was doing something wrong so i copy the code from document

`getOrders($marketplace_ids, $created_after, $created_before, $last_updated_after, $last_updated_before, $order_statuses, $fulfillment_channels, $payment_methods, $buyer_email, $seller_order_id, $max_results_per_page, $easy_ship_shipment_statuses, $next_token, $amazon_order_ids, $actual_fulfillment_supply_source_id, $is_ispu, $store_chain_store_id, $data_elements): \SellingPartnerApi\Model\Orders\GetOrdersResponse
`

and replaced one by one with NULL

`$response = $apiInstance->getOrders($marketplace_ids, $created_after, null, null, null, $order_statuses, null, null, null, null, $max_results_per_page, null, $next_token, null, null, null, null, $data_elements);`

Now finally it's working. 

Big thank you to all for your help and time.

**Comment by jlevers** [comment] 2022-04-14 21:02
Ah, sorry for the incorrect example, that's my bad. Glad you got it working.

**Comment by seannycrow** [comment] 2022-04-15 07:00
@jlevers I think you hit the nail on the head, we probably don't have PII access on our app, would you happen to know where we can request it? Thanks!

**Comment by sunil11475-dev** [comment] 2024-04-03 08:34
> Hi, I know this is an old topic. But looking at the solutions I still have the same problem. If I put @balicekt solution, but it tells me that the class newOrdersApi($this->getConfig()) does not exist. `Uncaught Error: Class 'OrdersApi' not found`
> 
> If I put the solution from @sunil11475-dev the response is empty `SellingPartnerApi\Model\OrdersV0\GetOrdersResponse Object ( [container:protected] => Array ( [payload] => SellingPartnerApi\Model\OrdersV0\OrdersList Object ( [container:protected] => Array ( [orders] => Array ( ) [next_token] => [last_updated_before] => [created_before] => 2024-04-03T03:58:32Z ) ) [errors] => [headers] => Array ( [Server] => Array ( [0] => Server ) [Date] => Array ( [0] => Wed, 03 Apr 2024 07:29:08 GMT ) [Content-Type] => Array ( [0] => application/json ) [Content-Length] => Array ( [0] => 64 ) [Connection] => Array ( [0] => keep-alive ) [x-amz-rid] => Array ( [0] => 0A70ZJY1NQBBRZE1A40E ) [x-amzn-RateLimit-Limit] => Array ( [0] => 0.04512 ) [x-amzn-RequestId] => Array ( [0] => 2e7d3936-7441-4da7-a4bc-ae7c039a91fe ) [x-amz-apigw-id] => Array ( [0] => OPF2e7d39367441 ) [X-Amzn-Trace-Id] => Array ( [0] => Root=1-660d0544-2e7d393674414da7 ) [Vary] => Array ( [0] => Content-Type,Accept-Encoding,User-Agent ) [Strict-Transport-Security] => Array ( [0] => max-age=47474747; includeSubDomains; preload ) ) ) )`
> 
> Someone help me please.

Can you please provide your code so i can check?

**Comment by sunil11475-dev** [comment] 2024-04-03 17:16
Everything looks fine.

$apiInstance = new SellingPartnerApi\Api\OrdersV0Api($config); 

Check the file, if you using updated version than class name may be changed - Find the Order class file and check the correct class name.

**Comment by sunil11475-dev** [comment] 2024-04-05 09:05
I had the same issue. You have open ticket with Amazon Developer to resolve this.
