### ISSUE TITLE
ApiException import missing

### ISSUE THREAD

**Issue by Kimmax** [jlevers/selling-partner-api#445] opened 2022-12-17 10:19 UTC
## Problem description:
API classes seem to be missing the import for `ApiException`.
Version: `5.5.0`

## Error:

For example:
```
PHP Fatal error:  Uncaught Error: Class 'SellingPartnerApi\Api\ApiException' not found in xx/vendor/jlevers/selling-partner-api/lib/Api/TokensV20210301Api.php:87
```

and many more. Adding the include fixes the problem.

**Comment by bigindian66** [comment] 2022-12-19 13:44
Hello !
I have the same issue here !
Is it ok to add the class manually ?
At least as a workaround until a fix is released ?

B.R.

**Comment by shodanto** [comment] 2022-12-19 14:26
same problem here

**Comment by steverobison** [comment] 2022-12-19 14:43
copy the APIException file into the api folder and change its namespace to SellingPartnerApi\Api

**Comment by scabudlan** [comment] 2022-12-19 15:16
> copy the APIException file into the api folder and change its namespace to SellingPartnerApi\Api. This fixed it for me as a quick fix.
> 
> namespace SellingPartnerApi\Api;

Thank you, the problem is solved.

**Comment by soseki-angfa** [comment] 2022-12-23 02:52
I guess he wants to use Exception from guzzel client.
Maybe, we wait for that.

**Comment by plegenza** [comment] 2022-12-23 09:11
Still getting error: "Error: Class 'SellingPartnerApi\Api\ApiException' not found in file /var/www/clients/client0/web4/laravel/vendor/jlevers/selling-partner-api/lib/Api/CatalogItemsV20220401Api.php on line 547"

**Comment by soseki-angfa** [comment] 2022-12-23 09:17
@plegenza 
This is not fixed yet.
You can just copy the ApiException.php to under Api folder and compile it the namespace.

**Comment by plegenza** [comment] 2022-12-23 09:21
@soseki-angfa I do that now, thanks. 
Comment by @scabudlan is confusing when for fast reading ;)

**Comment by jlevers** [comment] 2022-12-23 20:46
Sorry about this guys -- it's fixed in `v5.5.2`.

**Closed by jlevers** 2022-12-23 20:46 UTC

**Comment by bigindian66** [comment] 2022-12-24 11:46
Thank you very much for your reactivity !

**Comment by soseki-angfa** [comment] 2022-12-26 00:40
@jlevers 
Thanks for that.
We really appreciate it.
