### ISSUE TITLE
I am getting "Not authorized for requested operation","error":"unauthorized_client"

### ISSUE THREAD

**Issue by webmicah** [jlevers/selling-partner-api#31] opened 2021-05-26 19:45 UTC
I am getting "Not authorized for requested operation","error":"unauthorized_client"

**Comment by jlevers** [comment] 2021-05-27 01:09
Could you please share the complete piece of code that you're running that's causing this error?

**Comment by webmicah** [comment] 2021-05-27 04:48
I'm using this code. 

<?php
require_once(__DIR__ . '/vendor/autoload.php');

use SellingPartnerApi\ConfigurationOptions;
use SellingPartnerApi\Configuration;
use SellingPartnerApi\Api;

$configurationOptions = new ConfigurationOptions(
    "<LWA client ID>",
    "<LWA client secret>",
    "<LWA refresh token>",
    "<AWS access key ID>",
    "<AWS secret access key>",
    "us-east-1",
    "https://sellingpartnerapi-na.amazon.com",
);
$config = new Configuration($configurationOptions);

$api = new Api\SellersApi();
try {
    $result = $api->getMarketplaceParticipations();
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling SellersApi->getMarketplaceParticipations: ', $e->getMessage(), PHP_EOL;
}

?>

I put this in index.php on my root folder .

**Comment by jlevers** [comment] 2021-05-27 06:59
And just to make sure, you replaced the placeholders in the `ConfigurationOptions` object with your actual credentials?

If so, did you create your SP API application using an IAM role ARN or an IAM user ARN?

**Comment by webmicah** [comment] 2021-05-27 07:01
Yes I did and I create my SP API Application using my I AM user ARN. I did follow this this article you created. 

https://jesseevers.com/selling-partner-api-access/

The one roles that was checked was only Inventory and Order Management is that enough ?

**Comment by jlevers** [comment] 2021-05-27 07:06
No, you need the `Selling Partner Insights` article to be able to make the `getMarketplaceParticipations` call. That's almost certainly why you're getting the `unauthorized_client` error.

**Comment by webmicah** [comment] 2021-05-27 07:18
How can I enable Selling Partner Insights? Is it a role when I create a SP-API application ?

I change my code to get orders

require_once(__DIR__ . '/vendor/autoload.php');

$apiInstance = new SellingPartnerApi\Api\OrdersApi();
$order_id = '114-6237846-0499414'; // string | An Amazon-defined order identifier, in 3-7-7 format.

try {
    $result = $apiInstance->getOrder($order_id);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling OrdersApi->getOrder: ', $e->getMessage(), PHP_EOL;
}

but it says Access to requested resource is denied.", "code": "Unauthorized", "details":

**Comment by jlevers** [comment] 2021-05-31 16:44
We resolved this via a phone call (incorrect credentials) -- closing.

**Closed by jlevers** 2021-05-31 16:44 UTC

**Comment by iLoveSarabear** [comment] 2021-06-06 12:57
Hi @jlevers, can you give any tips about his credential issue? I'm having a similar problem and have double checked all settings in IAM.

**Comment by jlevers** [comment] 2021-06-07 03:57
It's hard for me to predict what the problem is without seeing your code, but the usual suspects are:
* Incorrect LWA or AWS credentials
* Trying to make calls to a part of the API that you don't have access to
* Having an incorrect system clock time

**Comment by iLoveSarabear** [comment] 2021-06-07 11:21
- I can confirm that the AWS credentials are correct because under IAM I see last activity "Today".
- I however don't any last activity update that under **Roles**, for the role I gave to Amazon Seller Central. So it's possible there's a problem there.
- I've contacted Amazon in an effort to get them to change the ARN they have on file to the "User" instead of the "Role. (No luck yet)
- The system clock is set to EDT, it appears correct (Ubuntu, running "date" command). It's possible I'm sending the wrong expiration date when making a call? I'm basically converting the EDT date to unixtime in php and sending that as an integer.

That's all I have, oAuth is working ok, I'm getting our tokens. Not sure what else it could be.

**Comment by jlevers** [comment] 2021-06-07 15:28
That all sounds correct -- what version of the library are you using? In the latest version (2.2.0) there is support for role-based authentication (see [the README](https://github.com/jlevers/selling-partner-api#using-the-configuration-and-configurationoptions-classes) for configuration details), but older versions don't support authenticating with an IAM role ARN.

**Comment by iLoveSarabear** [comment] 2021-06-07 18:14
Yeah, I'm on 2.2.0. I'll send an email with some screenshots.

Thanks
