### ISSUE TITLE
TAB delimited reports issue

### ISSUE THREAD

**Issue by 0xSekar** [jlevers/selling-partner-api#248] opened 2022-04-19 00:10 UTC
Hi again, today I started to have an issue with reports download. Weird thing is that it is happening only with some sellers and some tab delimited reports. Same report for other sellers still work as expected.

Basically the problem is that the result from the line https://github.com/jlevers/selling-partner-api/blob/e30bf3c42774a2656a2c8ef7ac5b7ca391d3bbaa/lib/Document.php#L140 is an array where on each row is a 2 elements array like this:

```
array(2) {
  ["item-name   item-description        listing-id      seller-sku      price   quantity        open-date       image-url       item-is-marketplace     product-id-type zshop-shipping-fee       item-note       item-condition  zshop-category1 zshop-browse-path       zshop-storefront-feature        asin1   asin2   asin3   will-ship-internationally       expedited-shipping       zshop-boldface  product-id      bid-for-featured-placement      add-delete      pending-quantity        fulfillment-channel     merchant-shipping-group"]=>
  string(212) "HP 14-fq0010ca Laptop, AMD 3020e Processor, 4GB RAM, 64GB eMMC Flash Storage, AMD Radeon Graphics, Windows 10 Home in S Mode, 10M49UA#ABL, Jet Black (Renewed)   0907YGSMBL5      10M49UA#ABL_R-TEK       194.95  0       2021-09-07 15"
  [""]=>
  NULL
}
```
From the output, it looks like PhpSpreadsheet is unable to detect the delimiter from the file. As mentioned, weird thing is that from many different sellers and countries it only happens for some of them and in some reports, mainly GET_MERCHANT_LISTINGS_INACTIVE_DATA and GET_MERCHANT_LISTINGS_ALL_DATA

A quick workaround was to replace:
https://github.com/jlevers/selling-partner-api/blob/e30bf3c42774a2656a2c8ef7ac5b7ca391d3bbaa/lib/Document.php#L138
with:

``` php
                $fileType = \PhpOffice\PhpSpreadsheet\IOFactory::identify($this->tmpFilename);
                $reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader($fileType);
                if($this->contentType === ContentType::TAB) {
                    $reader->setDelimiter("\t");
                }
                $spreadsheet = $reader->load($this->tmpFilename);
```
But was unable to detect the underlaying issue to make a cleaner fix. Any suggestion?

**Comment by jlevers** [comment] 2022-04-19 04:36
Damn, thought I'd fixed this problem. Could you send me the full contents of a couple reports where you're running into this? If they contain sensitive information, you can throw them in private gists and email them to me at `<my first name>@jesseevers.com`.

**Comment by 0xSekar** [comment] 2022-04-19 11:40
Thanks @jlevers , sent them to your email

**Comment by jlevers** [comment] 2022-04-21 02:46
For transparency -- as I said to you via email, this is an issue related to the fact that Amazon doesn't use double-quote delimiters in tabular data files, but PHPSpreadsheet interprets them as delimiters, so the document gets parsed incorrectly after the first double quote. Working on a fix.

**Comment by gregordonsky** [comment] 2022-04-27 16:44
Hi @jlevers,

I think you should create directly a CSV document from the Amazon response without parsing the string before on your own.

PhpSpreadsheet has the ability to parse correctly the CSV file formats; next lines should be the right CSV options:

```php
$reader = new \PhpOffice\PhpSpreadsheet\Reader\Csv();
$reader->setInputEncoding('UTF-8');
$reader->setDelimiter("\t");
$reader->setEnclosure('');
$reader->setSheetIndex(0);

$spreadsheet = $reader->load($this->tmpFilename);
```

However, if you want preserve the `preg_replace` function and you want that PHPSpreadsheet doesn't use double-quote delimiters this is the option to set for CSV:
```php
$reader->setEnclosure('');
```
but for explicit setting this option you need always to create a reader instance:

```php
$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReaderForFile($this->tmpFilename);
```
you cannot use the automatic mode:
https://github.com/jlevers/selling-partner-api/blob/e30bf3c42774a2656a2c8ef7ac5b7ca391d3bbaa/lib/Document.php#L138

Unfortunatly I was unable to reproduce the issue mentioned by @0xSekar because i don't have a report for testing this problem.

I have checked this issue because i have a problem with encodings.
I didn't figure out that i needed to pass `ISO-8859-1` to the download method or i get incorrect data.

**Comment by 0xSekar** [comment] 2022-04-27 21:24
Agree with @gregordonsky comment. This is basically how I temporally resolved the issue on my prod environment:

``` php
$fileType = \PhpOffice\PhpSpreadsheet\IOFactory::identify($this->tmpFilename);
$reader = \PhpOffice\PhpSpreadsheet\IOFactory::createReader($fileType);
if($this->contentType === ContentType::TAB) {
    $reader->setDelimiter("\t");
}
$spreadsheet = $reader->load($this->tmpFilename);
```
not tried reports that are not tab delimited as currently I'm not using them

**Comment by discover59** [comment] 2022-05-02 09:01
@jlevers Any update on this issue? I also have same issue.

**Comment by jlevers** [comment] 2022-05-02 21:59
Hey @gregordonsky, thanks for the feedback.

The problem is that if you read the source, `$reader->setEnclosure('');` actually results in the enclosure being set to a double-quote character. There is no way to set the reader to not have a enclosure character. If a report field contains a double quote at the beginning or end of a field, it will be interpreted as an enclosure character and cause issues.

https://github.com/PHPOffice/PhpSpreadsheet/blob/7169648a64f5810f5da9438bc1b8571e6109b42c/src/PhpSpreadsheet/Reader/Csv.php#L453-L461

For that reason, the `preg_replace` strategy is required to escape any double quotes at the start or end of a field, since they will otherwise be interpreted as enclosures by PhpSpreadsheet. 

I'll address the encoding issue you brought up separately (in #261).

**Comment by 0xSekar** [comment] 2022-05-02 22:28
@jlevers , setting the delimiters to \t as in https://github.com/jlevers/selling-partner-api/issues/248#issuecomment-1111498664 solved the issue at least in the example files I sent to you without needing to set enclosure.

**Comment by jlevers** [comment] 2022-05-02 22:32
Yep, it solves it in your original file, but that's because the double quotes in that file weren't at the beginning or end of a field -- they were in the middle. If you try the same approach, but with a report document with quotes at the beginning or end of a field, the parsing won't work correctly.

**Comment by 0xSekar** [comment] 2022-05-02 23:07
Correct, but you already escaped double quotes at the beginning of a field using preg_replace, you still get errors with the combo (preg_replace plus field delimiter)?

**Comment by gregordonsky** [comment] 2022-05-03 08:37
> For that reason, the `preg_replace` strategy is required to escape any double quotes at the start or end of a field, since they will otherwise be interpreted as enclosures by PhpSpreadsheet. I need to find a way to reliably address starting/ending double quotes and leave double quotes in the middle of a field alone, since it seems my current regex isn't doing that properly.

Thank you @jlevers, I didn't check the PhpSpreadsheet source and you are right.
As a workaround, you can set the enclosure character as a weird char.

So for example:
```php
$reader->setEnclosure(chr(0)); // NUL char
```

or
```php
$reader->setEnclosure(chr(8)); // Backspace char
```

So I think a good alternative is to set the delimiter to \t as @0xSekar suggest and the enclosure char:
```php
$reader = new \PhpOffice\PhpSpreadsheet\Reader\Csv();
$reader->setInputEncoding('UTF-8');
$reader->setDelimiter("\t");
$reader->setEnclosure(chr(8));
$reader->setSheetIndex(0);

$spreadsheet = $reader->load($this->tmpFilename);
```

**Comment by jlevers** [comment] 2022-05-16 22:42
Sorry that this took me so long to get around to, but @gregordonsky passing a strange character for the enclosure character worked like a charm -- I was able to get rid of the `preg_replace` calls altogether. Thank you, and thanks @0xSekar, for your help on this. The updated code is in `v5.0.0`.

**Closed by jlevers** 2022-05-16 22:42 UTC
