### ISSUE TITLE
It's redefine in "FbaOutbound\CurrentStatus"

### ISSUE THREAD

**Issue by lai3221** [jlevers/selling-partner-api#274] opened 2022-05-16 06:39 UTC
It's redefine in /lib/Model/FbaOutbound/CurrentStatus.php  
OUT_FOR_DELIVERY
DELIVERY_ATTEMPTED

**Comment by jlevers** [comment] 2022-05-16 21:47
Thanks -- this is a duplicate of #270, so I'm going to close this one and track the issue there.

**Closed by jlevers** 2022-05-16 21:47 UTC
