### ISSUE TITLE
At least 2 new issues in v5.2.1

### ISSUE THREAD

**Issue by sergeykalenyuk** [jlevers/selling-partner-api#350] opened 2022-07-28 12:57 UTC
@jlevers, I have found two new issues in v5.2.1:

1.
`if (!$this->signingScope && ($restrictedPath === null || $dataElements === [])) {`
was replaced with
`if (!$this->signingScope && $restrictedPath === null && $dataElements === []) {`.
in `\SellingPartnerApi\Authentication::signRequest`.
An order data cannot be retrieved anymore. It seems there is an issue with retrieving the restricted data token. I tested with the sandbox.
Error: `Amazon Selling Partner error: Response contained error: (400) InvalidInput: Could not match input arguments.`.

2.
The error occurred after fixing the argument types (https://github.com/jlevers/selling-partner-api/issues/314).
After this change, I replaced `$packageDimensions->setUnit(UnitOfLength::INCHES);` with `$packageDimensions->setUnit(new UnitOfLength(UnitOfLength::INCHES));`
but now there is an error:

Error: `Amazon Selling Partner error: Response contained error: (400) InvalidInput: Invalid request body: [instance type (object) does not match any allowed primitive type (allowed: ["string"]), instance value ({"value":"inches"}) not found in enum (possible values: ["inches","centimeters"]), format attribute "double" not supported, format attribute "int32" not supported].`

Please look into the issues above.
Thanks!

**Comment by 0xSekar** [comment] 2022-07-30 16:49
Agree that forcing RDT signing for orders API is an issue. Once RDT becomes mandatory on 7/31, orders should continue working without it but omitting PII data.

So for those that don't have the roles that allow PII data to be retrieved, the call should still work by using standard request signing. Maybe a parameter in the API config so you don't need to break auto generated code?

We are currently stuck at version 5.1.1 because an update will not allow us to fetch the orders until we get approval from amazon for the added roles.

**Comment by jlevers** [comment] 2022-07-30 17:32
hey @sergeykalenyuk, thanks for reporting.

issue 2 is fixed in `v5.2.2`, and i'm working on a fix for the situation that @0xSekar described above.

**Comment by jlevers** [comment] 2022-07-31 20:46
This should be fixed in `v5.2.3`, give it a try and let me know if you run into any more issues!

**Comment by sergeykalenyuk** [comment] 2022-08-01 10:21
@jlevers, the issue `signRequest` was fixed for `getOrder` but still persists for `\SellingPartnerApi\Api\MerchantFulfillmentV0Api::createShipmentWithHttpInfo`.
Host: `sandbox.sellingpartnerapi-na.amazon.com`.
Path: `/tokens/2021-03-01/restrictedDataToken`.
Response body: `[{"code":"InvalidInput","message":"Could not match input arguments"}]`.

**Comment by jlevers** [comment] 2022-08-01 15:46
the sandbox only supports very specific (static) calls -- i'm not surprised that this isn't working there. give the production endpoint a try and let me know if you're still having issues. you can read more about how the sandbox works here: https://developer-docs.amazon.com/sp-api/docs/selling-partner-api-sandbox

**Comment by sergeykalenyuk** [comment] 2022-08-01 16:33
@jlevers, thanks for the response. I am familiar with the sandbox. The shipping label creation with the sandbox works in `v5.1.1` but stopped working with the new versions.

**Comment by jlevers** [comment] 2022-08-02 16:28
Could you please share your code? I tried downgrading to `v5.1.1` and making a `createShipment` call to the sandbox, but I'm just getting a 403. On `v5.2.3`, I get the same error you do. I think that maybe on `v5.1.1` the RDT wasn't being generated at all for `createShipment`, which was why you weren't encountering this error?

**Comment by jlevers** [comment] 2022-08-05 05:43
Right, but per Amazon's docs, the RDT is required for that call -- so presumably calling that endpoint without providing an RDT is deprecated behavior, and will no longer work at some point in the future.

**Comment by sergeykalenyuk** [comment] 2022-08-09 20:33
@jlevers, yes, the RDT info is listed [here](https://developer-docs.amazon.com/sp-api/changelog/important-notice-discontinued-support-lwa-tokens-can-no-longer-retrieve-pii-in-selling-partner-api). The error message is about an invalid argument though. Please the exact error output [here](https://gist.github.com/sergeykalenyuk/0af2e03b6ebdf1a77928a7e2db73679e). I haven't found any info that the sandbox does not work with RDT. Could you please address the issue with the input arguments?

**Comment by jlevers** [comment] 2022-08-12 18:42
The reason this is an invalid argument is because the sandbox only accepts a limited set of inputs -- if you look at the [Tokens API model](https://developer-docs.amazon.com/sp-api/docs/tokens-api-v2021-03-01-model), the URL for the `createShipment` endpoint is not included in any of the valid sandbox input arguments. I believe that's why you're getting an `InvalidInput` error. Please try making a call to the production `createShipment` endpoint and let me know if you have the same problem -- if you don't, then we will have confirmed that the problem is with the sandbox rather than with how my library is handling RDT requests.

**Comment by jlevers** [comment] 2022-08-23 21:13
@sergeykalenyuk i'm going to close this, but if you'd like to discuss further please feel free to reopen it.

**Closed by jlevers** 2022-08-23 21:13 UTC
