### ISSUE TITLE
Error in getShipments in FbaInboundV0Api.

### ISSUE THREAD

**Issue by Sri0311** [jlevers/selling-partner-api#556] opened 2023-06-16 05:23 UTC
## Problem description:

Having error while using getShipments in FbaInboundV0Api. With Marketplace id "A2VIGQ35RCS4UG"

## Error:
```
# invalid length for $district_or_county when calling Address., must be smaller than or equal to 25.
```

## Code

```php
// Your code here...PLEASE make sure to redact secrets from your code!
```

## Seller Central SP API config page screenshot

*your screenshot here*

**Comment by jlevers** [comment] 2023-07-03 18:01
I'm hesitant to remove this length limitation, because I don't know if Amazon will accept requests that have district/county names that are longer than 25 characters. If you want to test that out, you can remove these 3 lines of code from your local copy of the library:

https://github.com/jlevers/selling-partner-api/blob/6eb73b7e827e13b95bb43e12e8b812050544e5e4/lib/Model/FbaInboundV0/Address.php#L192-L194

And then try making the request with a >25 character district/county value, and see if they accept the request.

**Comment by jlevers** [comment] 2023-07-10 15:36
This is duplicate of #557, closing

**Closed by jlevers** 2023-07-10 15:36 UTC
